# Generated by Django 2.2.24 on 2022-01-22 15:26
from django.db import migrations


def add_owner_flats(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        owner, _ = Owner.objects.get_or_create(
            name=flat.owner,
            phone=flat.owners_phonenumber
        )
        owner.flats.add(flat)
        owner.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20220202_1040'),
    ]

    operations = [
        migrations.RunPython(add_owner_flats),
    ]
